### ISSUE TITLE
Investigate status disconnecting from PR

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests-gh-bridge#19]
Looking at this PR it doesn't look like the wp-desktop canary test was run at all - https://github.com/Automattic/wp-calypso/pull/20828

But they were run here - https://circleci.com/gh/Automattic/wp-desktop/11219

I'm not sure whether the status ever showed up or if it was disconnected later.

cc: @astralbodies

**Comment by hoverduck** [comment]
What's happening here is that the developer creates a PR and adds the `[Status] Needs Review` label, which kicks off the tests.  But then afterward they push more changes to the branch, and the status is disconnected (as it's no longer accurate).

@alisterscott What if we updated the hook to look for more events so we could handle this situation?  So the tests would run if A) the Needs Review label is applied, or B) A commit is pushed and the label is already present?  Do we get the information on existing labels when a commit event is fired?

**Comment by alisterscott** [comment]
> @alisterscott What if we updated the hook to look for more events so we could handle this situation? So the tests would run if A) the Needs Review label is applied, or B) A commit is pushed and the label is already present? Do we get the information on existing labels when a commit event is fired?

Yes, this will be possible for sure - you can query the labels for the PR when a push event is run

**Comment by alisterscott** [comment]
We probably should do this for the canary tests as well - @markryall asked me about this exact thing
